gameURLS = [
  {"name": "Slope", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/slope.html"},
  {"name": "Tunnel Rush", "url": "https://66119cb41328d7b557e39273.oyopages.com/view.html"},
  {"name": "Retro Bowl", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Retro%20Bowl/index.html"},
  {"name": "1v1.lol", "url": "https://cutlass.mos.us-south-1.sufybkt.com/1v1-lol/index.html"},
  {"name": "Apple Shooter", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/apple-shooter.html"},
  {"name": "Among Us", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/among-us.html"},
  {"name": "Bitlife", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/bitlife.html"},
  {"name": "The Impossible Quiz", "url": "https://661465431328d7b557e3931b.oyopages.com/view.html"},
  {"name": "Tanuki Sunset", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Tanuki%20Sunset/index.html"},
  {"name": "Fall.io", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Fall.io/index.html"},
  {"name": "Bloons Tower Defense", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/bloons-tower%20defense.html"},
  {"name": "Temple Run", "url": "https://archive777.com/Temple%20Run/Temple%20Run%202%20Game/"},
  {"name": "Basketball Stars", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/basketball-stars.html"},
  {"name": "Vex 5", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/vex-5.html"},
  {"name": "Spacebar Clicker", "url": "https://script.google.com/macros/s/AKfycbzZN3jRO2eOgcp622_W0GYAeArMio71AmlfRhF8yFucC5hEbRnDFZ3NLiN8peebEdlhWw/exec"},
  {"name": "Learn To Fly", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/learn-to-fly.html"},
  {"name": "Rooftop Snipers", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/rooftop-snipers.html"},
  {"name": "Paper.io 2", "url": "https://script.google.com/macros/s/AKfycbwNxCzUuQVmLRWTwYK2D4yTqpWg2O-qge8BwCkxhLmqWd1DtXynwJXPEDClPt7ERZr-/exec"},
  {"name": "JustFall.lol", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/just-fall.html"},
  {"name": "Gun Mayhem", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/gun-mayhem.html"},
  {"name": "Gun Mayhem 2", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/gun-mayhem-2.html"},
    {"name": "Portal", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/portal.html"},
    {"name": "Cookie Clicker", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/cookie-clicker.html"},
    {"name": "Car Simulator", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Car%20Simulator/index.html"},
    {"name": "Subway Surfers", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/subway-surfers.html"},
    {"name": "Bloons Tower Defense 4", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/bloons-tower-defense-4.html"},
    {"name": "Taxi Drift", "url": "https://script.google.com/macros/s/AKfycbw5OBrDuUEcIA8zhAOiNU3U800gv3niOBqf44VIjv1ZfndCgav4OxoEPHS1ZLRCwHUnHg/exec"},
    {"name": "Hole.io", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/hole.io.html"},
    {"name": "Pixel Shooter", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/pixel-shooter.html"},
    {"name": "Smash Karts", "url": "https://script.google.com/macros/s/AKfycbx63iRe5mtf5PQGIn_eGwKePxCA1iU6w-YApn57Mh4phi2ZB-G-GCJA1YTV9jKrwoqb/exec"},
    {"name": "TABS", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/tabs.html"},
    {"name": "Time Shooter 3 SWAT", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/time-shooter-3-swat.html"},
    {"name": "FNAF", "url": "https://script.google.com/macros/s/AKfycbxJNtrKTWPCSIo9tOqq53G2xqoQCIPDTYUsVOT79Eqk8I7C5cQkGdDnj0jzlNHa7bvs3g/exec"},
    {"name": "Rocket League", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Rocket%20Soccer%20Derby/index.html"},
    {"name": "Cluster Rush", "url": "https://661463761328d7b557e39319.oyopages.com/view.html"},
    {"name": "Minecraft 1.8.8", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/eaglercraftx.html"},
    {"name": "Minecraft Resent", "url": "https://cutlass.mos.us-south-1.sufybkt.com/mcresent.html"},
    {"name": "Minecraft Flame", "url": "https://cutlass.mos.us-south-1.sufybkt.com/flameclient%203.7.html"},
    {"name": "Minecraft Astra", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/eaglercraft-astra-client.html"},
    {"name": "Minecraft 1.9.4", "url": "https://cutlass.mos.us-south-1.sufybkt.com/EaglercraftL_1.9_v0_7_0_Offline_Signed.html"},
    {"name": "Minecraft 1.11.2", "url": "https://cutlass.mos.us-south-1.sufybkt.com/EaglercraftZ1.11.html"},
    {"name": "Minecraft Tuff 1.12.2", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Tuff%20Client/index.html"},
    {"name": "Roblox Color Run", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/rbx-color-run.html"},
    {"name": "Roblox Blade Ball", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/blade-ball-rbx.html"},
    {"name": "Roblox Obby", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/rbx-obby.html"},
    {"name": "Roblox Rob The Bank", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/rbx-rob-the-bank.html"},
    {"name": "Tomb of the Mask", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/tomb-of-the-mask.html"},
    {"name": "Monkey Mart", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Monkey%20Mart/index.html"},
    {"name": "Blockpost", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Blockpost/index.html"},
    {"name": "Moto X3M", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/moto-x3m.html"},
    {"name": "Bob The Robber", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/bob-the-robber.html"},
    {"name": "Geometry Dash", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Geometry%20Dash/index.html"},
    {"name": "Stick War", "url": "https://script.google.com/macros/s/AKfycbw6ZtLTvS_AkT86pJbNZK61tdfDTo_tio_QIXcEZfx8QPlr1ty-Sm0bMSbUyJYc6rGRRA/exec"},
    {"name": "Flash Games", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/flash-game-launcher.html"},
    {"name": "Polytrack", "url": "https://cutlass.mos.us-south-1.sufybkt.com/polytrack/index.html"},
    {"name": "Fury Wars", "url": "https://cutlass.mos.us-south-1.sufybkt.com/fury%20wars/index.html"},
    {"name": "Stickman Hook", "url": "https://cutlass.mos.us-south-1.sufybkt.com/StickmanHook/index.html"},
    {"name": "Minecraft Parkour", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/mc-parkour.html"},
    {"name": "Skibidi Toilet.io", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/skibiditoilet.io.html"},
    {"name": "Tiny Fishing", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/tiny-fishing.html"},
    {"name": "Space Waves", "url": "https://crazygames.cdn.msnfun.com/9nm5764dbppg/v6/index.html"},
    {"name": "Gangsta Island", "url": "https://playgama.cdn.msnfun.com/9p87g58gdfs8/v20/index.html"},
    {"name": "Smashy Road", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Smashy%20Road/index.html"},
    {"name" : "Trash Clash Royale", "url" : "https://cutlass.mos.us-south-1.sufybkt.com/Clash%20Royale%20Trash/index.html"},
    {"name" : "Steal a Brainrot", "url" : "https://crazygames.cdn.msnfun.com/9pltx207s22g/v3/index.html"},
    {"name" : "Grow a Garden", "url" : "https://script.google.com/macros/s/AKfycbwK_YDMKEccZyVOz_fpe66G4Je4VyFPdT10OdaKpM699Utzbq41n2m6OXqAzpX0oqrLTA/exec"},
    {"name" : "Plants vs Brainrots", "url" : "https://cutlass.mos.us-south-1.sufybkt.com/Plants%20vs%20Brainrots/index.html"},
    {"name" : "Masked Special Forces", "url" : "https://storage.googleapis.com/freezenova/all/2022/unity2/masked-special-forces/index.html"},
    {"name" : "Plants vs Zombies", "url" : "https://script.google.com/macros/s/AKfycby_ln3ql4aO56lxfeLUH_UziAcZvRzETmL9zqekK0neuz5OHISrr6getE8_-or9E_Tj/exec"},
    {"name" : "Crazy Cattle 3D", "url" : "https://cutlass.mos.us-south-1.sufybkt.com/CrazyCattle3D/index.html"},
    {"name": "OvO", "url": "https://script.google.com/macros/s/AKfycbyDZOJq86UIFlMkKfvZtA_Sv86sKooVRpwVFS2rb38TOT8ExCt3PfR1Y5UAveVuVGlQLw/exec"},
    {"name": "Drive Mad", "url": "https://cutlass.mos.us-south-1.sufybkt.com/drive-mad-main/index.html"},
    {"name": "Run 3", "url": "https://script.google.com/macros/s/AKfycbzH19beOtthmgHOAyQwTzkPrGUquWfIq91ElX_xLebPeMZTByPCWbHpMX2ANYTjcTjs/exec"},
    {"name": "Duck Life 3", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/duck-life-3.html"},
    {"name": "Duck Life 5", "url": "https://script.google.com/macros/s/AKfycbw3sy-Wq6nxyUpV0HOn0KE-M7vYfdnBq4uk0kw8HArdPIxVkpKqwV6KBhYF340z2ahQ/exec"},
    {"name": "Block Blast", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Block%20Blast/index.html"},
    {"name": "Happy Wheels", "url": "https://script.google.com/macros/s/AKfycbyfMPVIGx6dJPrYKeE9e4Erj949-dH28pWVRjdV1vgnoylpBV8af03JNLoz2MwAIBLECg/exec"},
    {"name": "Doodle Jump", "url": "https://script.google.com/macros/s/AKfycbz9ZJCJhSWY_L-w8eDd3YKJVCPtmVikRpLFXZo9chsP9Ui1bASy8inKly0D7odsrgHbJw/exec"},
    {"name": "Drift Boss", "url": "https://script.google.com/macros/s/AKfycbwAOi2tPbjzeWDkigfZMIPEGubYxz2la_qjxJyydNZyjwgbqsv9mv05g7tdmLHdvdaw/exec"},
    {"name": "Henry Stickmin", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Henry%20Stickmin%20Collection/index.html"},
    {"name": "Hollow Knight", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/hollow-knight.html"},
    {"name": "Infinite Craft", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/infinite-craft.html"},
    {"name": "Raft", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/raft.html"},
    {"name": "Brawl Heroes", "url": "https://marketjs.cdn.msnfun.com/9pk3b4qcbtck/v22/index.html"},
    {"name": "Ultrakill", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/ultrakill.html"},
    {"name": "Angry Birds", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/angry-birds.html"},
    {"name": "My Friend Pedro", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/my-friend-pedro.html"},
    {"name": "99 Nights in the Forest", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/99-nights.html"},
    {"name": "Deltarune", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/deltarune.html"},
    {"name": "Undertale Yellow", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Games/undertale-yellow.html"},
];

adminGames = [
  {"name": "Unblocker (BETA)", "url": "https://cutlass.mos.us-south-1.sufybkt.com/Unblocker/index.html"},
]
gameURLS.push({"name" : "Request Games", "url" : "https://cutlass.mos.us-south-1.sufybkt.com/GameRequests/submit.html"})
document.querySelector("title").innerText = "Google Classroom";
